# PACKAGES


# INSTALL
# install.packages("dplyr")
# install.packages("rlist")
# install.packages("data.table")
# install.packages("rlist")
# install.packages("RCurl")
# install.packages("glmnet")
# install.packages("arm")
# install.packages("ggplot2")
# install.packages("stringr")
# install.packages("psych")
# install.packages("aod")
# install.packages("QuantPsyc")
# install.packages("R.matlab")
# install.packages("swirl")
# install.packages("XML")
# install.packages("lubridate")
# install.packages("zoo")
# install.packages("xlsx")
# install.packages("rJava")
# install.packages("gdata")
# install.packages("combinat")
# install.packages("ISLR")
# install.packages("caret")
# install.packages("stringi")
# install.packages("scrapeR")
# install.packages("httr")
# install.packages("rvest")
# install.packages("GGally")
# install.packages("kernlab")
# install.packages("randomForest")
# install.packages("e1071")
# install.packages("pROC")
# install.packages("jpeg")
# install.packages("ggROC")
# install.packages("mlbench")
# install.packages("pwr")
# install.packages("ROCR")
# install.packages("quantmod")
# install.packages("fields")
# install.packages("C50")
# install.packages("AppliedPredictiveModeling")
# install.packages("class")
# install.packages("boot")
# install.packages("gbm")
# install.packages("moments")
# install.packages("Hmisc")
# install.packages("pracma")
# install.packages("klaR")
# install.packages("rpart")
# install.packages("ellipse")
# install.packages("ipred")
# install.packages("MASS")
# install.packages("RWeka")
# install.packages("penalizedLDA")
# install.packages("Amelia")
# install.packages("corrgram")
# install.packages("R.matlab")
# install.packages("lsr")
# install.packages("ez")
# install.packages("NCmisc")
# install.packages("gmodels")
# install.packages("Sweave")
# install.packages("plotly")
# install.packages("forecast")
# install.packages("Rmisc") 
# install.packages("tidyr")
# install.packages("miscTools")
# install.packages("plotrix")
# install.packages("car")
# install.packages("coin")
# install.packages("lsmeans")
# install.packages("dunn.test")
# install.packages("LogicReg")
# install.packages("Sweave")
# install.packages("stargazer")
# install.packages("htmlTable")
# install.packages("memisc")
# install.packages("texreg")
# install.packages("R.matlab")
# install.packages("multcomp")
# install.packages("sna")
# install.packages("knitr")
# install.packages("xtable")
# install.packages("pander")
# install.packages("gdata")
# install.packages("formattable")
# install.packages("ezknitr")
# install.packages("broom")
# install.packages("DMwR")
# install.packages("tsModel")
# install.packages("cowplot")
# install.packages("vcd")
# install.packages("doParallel")
# install.packages("stepPlr")
# install.packages("tidyverse")
#install.packages("phylogram")
# install.packages("ggdendro")
# install.packages("dendextend")
# install.packages("ggraph")
# install.packages("circlize")
# install.packages("dynamicTreeCut")
# devtools::install_github("emvolz-phylodynamics/treestructure")

# LIBRARY

# Frequently used:
library(plyr)
library(ggplot2)
library(gridExtra)
library(data.table)
library(evobiR)
library(tidyverse)
library(ggtree)
library(phylogram)
library(readr)
library(ape)
library(ggdendro)
library(dendextend)
library(ggraph)
library(cluster)
library(circlize)
library(phytools)
library(dplyr)
library(data.table)
library(plyr)
library(dynamicTreeCut)
library(factoextra)
library(textclean)
library(ggplot2)
library(gridExtra)
library(amap)
library(devtools)
library(treestructure)
library(grid.text)


# Other:

# library(dplyr)
# library(rlist)
# library(data.table)
# library(rlist)
# library(RCurl)
# library(glmnet)
# library(arm)
# library(XML)
# library(ggplot2)
# library(stringr)
# library(lubridate)
# library(zoo)
# library(xlsx)
# library(rJava)
# library(gdata)
# library(combinat)
# library(ISLR)
# library(caret)
# library(stringi)
# library(scrapeR)
# library(httr)
# library(rvest)
# library(GGally)
# library(kernlab)
# library(randomForest)
# library(e1071)
# library(pROC)
# library(ggROC)
# library(mlbench)
# library(pwr)
# library(ROCR)
# library(jpeg)
# library(quantmod)
# library(fields)
# library(C50)
# library(AppliedPredictiveModeling)
# library(class)
# library(LogicReg)
# library(boot)
# library(moments) 
# library(Hmisc)
# library(pracma)
# library(klaR)
# library(rpart)
# library(ellipse)
# library(ipred)
# library(MASS)
# library(penalizedLDA)
# library(Amelia)
# library(corrgram)
# library(lsr)
# library(multcomp)
# library(ez)
# library(NCmisc)
# library(gmodels)
# library(Sweave)
# library(plotly)
# library(forecast)
# library(Rmisc)
# library(tidyr)
# library(miscTools)
# library(plotrix)
# library(car)
# library(coin)
# library(lsmeans)
# library(dunn.test)
# library(knitr)
# library(stats)
# library(xtable)
# library(stargazer)
# library(htmlTable)
# library(memisc)
# library(texreg)
# library(R.matlab)
# library(sna)
# library(pander)
# library(gdata)
# library(formattable)
# library(broom)
# library(DMwR)
# library(tsModel)
# library(gbm)
# library(survival)
# library(splines)
# library(parallel)
# library(cowplot)
# library(vcd)
# library(latticeExtra)
# library(doParallel)
# library(stepPlr)

